Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Metrics/AbcSize:
  Severity: warning
Metrics/ClassLength:
  Severity: warning
Metrics/CyclomaticComplexity:
  Severity: warning
Metrics/MethodLength:
  Severity: warning
Metrics/ModuleLength:
  Severity: warning
Metrics/PerceivedComplexity:
  Severity: warning

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SymbolArray:
  EnforcedStyle: brackets
