Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Metrics/AbcSize:
  Severity: warning
Metrics/MethodLength:
  Severity: warning
Metrics/PerceivedComplexity:
  Severity: warning

Style/FrozenStringLiteralComment:
  Enabled: false
