development:
  secret_key_base:

test:
  secret_key_base:

research:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

uat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

training:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

civmiguat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>