development:
  secret_key_base:

test:
  secret_key_base:

uat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

civmiguat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>