name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-ruby@v1.0.0
      with:
        ruby-version: '2.6.x'
    - run: yarn install
    - run: gem install bundler
    - run: bundle install
    - run: ./bin/rails test