name: Continuous Integration

on: push

jobs:
  build:
    name: build, test and deploy (on master only)
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps: 
    - name: 'Install Postgres client'
      run: sudo apt-get -yqq install libpq-dev
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-ruby@v1.0.0
      with:
        ruby-version: '2.6.x'
    - run: yarn install
    - run: gem install bundler
    - run: bundle install
    - name: Run tests 
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        bin/rails db:setup
        ./bin/rails test
    
    - name: Install the CF CLI
      if: github.ref == 'refs/heads/master'
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf-cli
    
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        CF_APP: funding-frontend-staging
        CF_SPACE: sandbox
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      run: |
        cf api https://api.london.cloud.service.gov.uk
        cf auth
        cf target -o national-lottery-heritage-fund -s ${CF_SPACE}
        cf v3-cancel-zdt-push ${CF_APP} || true
        cf v3-apply-manifest -f manifest.yml
        cf v3-zdt-push ${CF_APP}  --wait-for-deploy-complete